version: '3'
services:
  proxy.raiseup.local:
    image: nginx
    container_name: proxy
    init: true
    volumes:
      - ./services/devproxy/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
    environment:
      NGINX_PORT: 80
    depends_on:
      # - riseup.local
      - api.riseup.local

  # riseup.local:
  #   container_name: client
  #   build:
  #     context: ./apps/client
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./apps/client:/app
  #   depends_on:
  #     - api.riseup.local

  api.riseup.local:
    tty: true
    stdin_open: true
    container_name: api
    init: true
    build:
      context: ./apps/api
    env_file:
      - ./config/api.env
    volumes:
      - ./apps/api:/app
    ports:
      - 3000:3000
    depends_on:
      - database.riseup.local

  database.riseup.local:
    image: postgres:12.0-alpine
    container_name: database
    init: true
    volumes:
      - ./data/database:/var/lib/postgresql/data
    env_file:
      - ./config/database.env
    ports:
      - 5432:5432
